### ISSUE TITLE
Could you give the time spend example?

### ISSUE THREAD

**Issue by happyfrank** [cysmith/neural-style-tf#11]
Your job is wonderful. Could you give me the time spend example when you use GPU?

**Comment by cysmith** [comment]
Hi Frank,

For a 512x512 pixel image on my GTX 1080 it takes about 3 minutes for 1000 iterations. It is difficult to compare benchmarks to the popular Torch implementation because the author used a Maxwell and Pascal Titan X which are faster than my 1080.

By the way, I've visited your website before.  I found your implementation wonderful as well.

Cam

**Comment by happyfrank** [comment]
Thanks Cam.

**Comment by cysmith** [comment]
Haha. Oops
